### ISSUE TITLE
[Feature Request] Window matches image size: When rotating images AND Double Click: Toggle Original Size

### ISSUE THREAD

**Issue by Pachuriche** [jdpurcell/qView#10]
Specifically When rotating images + When opening images.

**Comment by jdpurcell** [comment]
1) I didn't add a new setting for it, but if "Window matches image size" is set to "When opening images", it will now auto-size the window after rotating.
2) I added an option (in the Image category) called "Original Size functions as toggle". If you turn that on, and customize the mouse action for double click to be "Original Size", it should do what you want.

Both changes are in the latest release.
