### ISSUE TITLE
Images opening in Original Size can be in weird locations if previous window size didn't match new image's size

### ISSUE THREAD

**Issue by Thespikedballofdoom** [jdpurcell/qView#7]
**Environment:**
- OS: [Windows 10]
- qView version: 2024-07-13.a2d0e95

**Information:**
I believe this is caused by images only being repositioned if they are changed in size, so Original size leaves them hanging even though it set the window size correctly.
It might be because I'm on 2 monitors, but I'm really unsure because they seem to go in directions related to the last image thatw as open.
![image](https://github.com/user-attachments/assets/86d57f75-0b3b-49d1-b2f6-7e7efeffded4)

**Comment by jdpurcell** [comment]
I attempted a fix for this in the [latest build](https://github.com/jdpurcell/qView/actions/runs/10345005585/artifacts/1800048316), hopefully it's okay now.
