### ISSUE TITLE
Original size images rotate from top-left corner, zoom to fit rotates from center

### ISSUE THREAD

**Issue by Thespikedballofdoom** [jdpurcell/qView#8]
**Information:**
It can even go offscreen resulting in the image completely vanishing.

Constrain image can help solve this, but it makes zooming in to the corners of images a chore by pulling the image away from you and forcing the corner of the image to be in the real corner of the whole window.

**Comment by jdpurcell** [comment]
Fixed! The latest Win64 build is [here](https://github.com/jdpurcell/qView/actions/runs/11098225182/artifacts/1993425693) if you'd like to try it.

**Comment by Thespikedballofdoom** [comment]
thank you man!
