### ISSUE TITLE
[Feature Request] Always-on-top functionality and slideshow timer

### ISSUE THREAD

**Issue by kaaamos** [jdpurcell/qView#9]
I've been using this program on top of art programs when I need to draw from reference, but it only stays on top if it's on slideshow mode, it's one of the best image viewers I've ever used.

My request is this, either:

1. A shortcut to enable always-on-top functionality.
2. Slideshows already have always-on-top function, but they have an obligatory timer. If you input 0 on the timer interval, it will only go ahead to the next image if you change the image manually, then the slideshow could act basically as an always-on-top toggle.

Thank you.

**Comment by jdpurcell** [comment]
I just added a "Window On Top" option, it's in the View menu and you can set a keyboard shortcut for it if you want. It's in the latest release.
